# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Personal Blog of Taewoo
email: touktw@gmail.com


name: "Taewoo"
url: "http://touktw.github.io"
description: "Personal Blog of Taewoo"
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: touktw
github_username:  touktw

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

#comments
comments :
  provider : disqus
  disqus :
    short_name : Taewoo

